### ISSUE TITLE
"AltServer has failed."

### ISSUE THREAD

**Issue by Aurillium** [altlinux-team/AltLinux#4]
Every time I try to install AltStore I get some variation of this error:
```
Date: 2022-10-03T08:31:14Z
Received auth response status code: 200
Received auth response status code: 200
Alert: Could not install AltStore.ipa to unknown.
    Unable to sign you in to your Apple ID. Try again later. (-36607)
Press any key to continue...
```

Then my phone asked me if I wanted to allow the sign-in and gave me a verification code and I tried to install AltStore again. I was prompted for the verification code and got this:

```
Received auth response status code: 200
Alert: Could not install AltStore.ipa to unknown.
    Unable to sign you in to your Apple ID. Try again later. (-36607)
Press any key to continue...
Error: com.rileytestut.AltServer.Localized (-36607).
Finished!
```

Since then I've gotten nowhere, restarting AltLinux hasn't helped and neither has trying to reinstall AltStore
I should mention: I was only asked for the verification code from AltLinux once, the other times it's gone straight to the second error.

**EDIT:** After going around and around like this several times I finally got it to log in, but now I have this error:
```
Received 2FA response status code: 200
Alert: Could not install AltStore.ipa to unknown.
    This device is already associated with other accounts in the Apple Developer Program or the Apple Developer Enterprise Program. Please use a different device. (-38607)
Press any key to continue...
Error: com.rileytestut.AltServer.Localized (-38607).
Finished!
```
I believe this one is an Apple problem though, I'm just not sure

**Comment by Aurillium** [comment]
Update: it's the next morning and I'm getting the first error repearedly and it's no longer giving me the notification on my phone to authorise the login

**Comment by SoftwareRat** [comment]
Fix: Host yourself an Anisette Server: https://github.com/NyaMisty/AltServer-Linux/releases/tag/v0.0.5

**Comment by sbot50** [comment]
> Fix: Host yourself an Anisette Server: https://github.com/NyaMisty/AltServer-Linux/releases/tag/v0.0.5

Great solution, doesn't seem to work tho. Also for some reason the port is 0.0.0.0:6969 might have smth todo with it but couldnt find anything about it.

**Comment by ArrowAced** [comment]
> Fix: Host yourself an Anisette Server: https://github.com/NyaMisty/AltServer-Linux/releases/tag/v0.0.5

I did this and I'm still getting the error. I don't know what I did wrong

**Comment by sbot50** [comment]
> > Fix: Host yourself an Anisette Server: https://github.com/NyaMisty/AltServer-Linux/releases/tag/v0.0.5
> 
> I did this and I'm still getting the error. I don't know what I did wrong

I fixed it by building it myself

**Comment by maxasix** [comment]
This should be fixed now.
Remove the contents of the $HOME/.local/share/altlinux folder and try running the script without installing.
