### ISSUE TITLE
AltJit and wifi sync doesn't work with AUR 

### ISSUE THREAD

**Issue by MrArdillo** [altlinux-team/AltLinux#7]
I'm using ArcoLinux with the AUR version

**Comment by maxasix** [comment]
Duplicate of #5

**Comment by MrArdillo** [comment]
Can you package that together with the AUR version to full functionality?

**Comment by maxasix** [comment]
Not how it works

**Comment by MrArdillo** [comment]
Okay, but can you make a tutorial in the description of the git for knowing how to configure it please?

**Comment by maxasix** [comment]
If you have a tutorial then I'd be glad to add it.

**Comment by MrArdillo** [comment]
In their repository they put this

Install usbmuxd for your distribution
Download netmuxd from the releases and place it somewhere permanent
Install screen and open run a new screen like so screen -S netmuxd
Run netmuxd like ./netmuxd --disable-unix --host 127.0.0.1, then press control a+d to escape the screen
Start a new screen for AltServer like screen -S altserver
Set the environment variable like export USBMUXD_SOCKET_ADDRESS=127.0.0.1:27015
Run AltServer ./AltServer-x86_64
